###
GET http://localhost:3004/clients

### creando un cliente
POST http://localhost:3004/clients
Content-Type: application/json

{
  "name":"Carlos ramos",
  "phone":"3146491024",
  "email":"carlosrgonzales88@gmail.com",
  "password":"1234567",
  "image":"https://ui-avatars.com/api/?name=ric+obs"
}
### un cliente crea una review
POST http://localhost:3004/clients/review
Content-Type: application/json

{ 
  "email":"jeevanrojas@gmail.com",
  "comment":"Muy buena",
  "rate":5, 
  "location":"AbsoluteFit - Sede Bernal"
}
###
GET http://localhost:3004/clients
