### obteniendo empleados
GET http://localhost:3004/empleado

### creando un empleado
POST http://localhost:3004/empleado
Content-Type: application/json

{
  "name":"ricardo",
  "email":"ricardo1@gamil.com",
  "phone":"123123",
  "password":"1234Ac",
  "account":true,
  "image":"https://ui-avatars.com/api/?name=ric+ob"
} 
