###
GET http://localhost:3004/suscription
###
POST http://localhost:3004/suscription
Content-Type: application/json

{ 
  "name":"Plata",
  "price":"3000",
  "description":"estpo es un suscripcion"
} 
