###
GET http://localhost:3004/training
###
POST http://localhost:3004/training
Content-Type: application/json

{ 
  "idClient":2,
  "name":"boxeo",
  "image":"https://ui-avatars.com/api/?name=ric+ob",
  "timeSlot":"hoy"
} 

