###
GET http://localhost:3004/trainings
###
GET http://localhost:3004/training/1
###
POST http://localhost:3004/training
Content-Type: application/json

{ 
  "idClient":2,
  "name":"boxeo",
  "image":"https://ui-avatars.com/api/?name=ric+ob",
  "timeSlot":"hoy"
} 

PUT http://localhost:3004/training/1
Content-Type: application/json

{ 
  "idClient":2,
  "name":"boxeo",
  "image":"https://ui-avatars.com/api/?name=ric+ob",
  "timeSlot":"hoy"
} 
###
DELETE http://localhost:3004/training/1
